### ISSUE TITLE
Mobile app support ( Android & IOS )

### ISSUE THREAD

**Issue by minkcrypto-zz** [cpuchain/electrum-cpu#2]
We will use Electrum-CPU as an alternative for other bitcoin based mobile wallet applications ( Coinomi, Bitcoin Wallet ( Java ), etc.)

Android build is available but they don't work properly ( Maybe y-chan will be able to handle this issue )

IOS build is being developed and used by Electron-Cash and the PR for electrum is available here ( https://github.com/spesmilo/electrum/pull/4795 )

**Comment by y-chan** [comment]
Android build is fixing now.
But, iOS build is I think we should not build until electrum's thing is formally merged.

**Comment by y-chan** [comment]
Ah....
I fixed Android build.
But, operation is very slowly...

**Comment by minkcrypto-zz** [comment]
Closing as per https://github.com/cpuchain/electrum-cpu/pull/4
